[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
simple-hook = "GLJosyGfzpEH1YRpek8rDnSBK8NG8vD3V7At3LwZCp43"
transfer_hooks = "C8sHNustasu4BJ6nM1StfBBvsBsfc3bsrZYsMihiYLzE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/emilemilovroydev/phantomWallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
